<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace WriterAi\SDK\Models\Operations;

use \WriterAi\SDK\Utils\SpeakeasyMetadata;
class CreateModelCustomizationRequest
{
	#[SpeakeasyMetadata('request:mediaType=application/json')]
    public \WriterAi\SDK\Models\Shared\CreateCustomizationRequest $createCustomizationRequest;
    
	#[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=modelId')]
    public string $modelId;
    
	#[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=organizationId')]
    public ?int $organizationId = null;
    
	public function __construct()
	{
		$this->createCustomizationRequest = new \WriterAi\SDK\Models\Shared\CreateCustomizationRequest();
		$this->modelId = "";
		$this->organizationId = null;
	}
}
