<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace WriterAi\SDK\Models\Operations;

use \WriterAi\SDK\Utils\SpeakeasyMetadata;
class DeleteFileRequest
{
	#[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=fileId')]
    public string $fileId;
    
	#[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=organizationId')]
    public ?int $organizationId = null;
    
	public function __construct()
	{
		$this->fileId = "";
		$this->organizationId = null;
	}
}
