<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace WriterAi\SDK\Models\Operations;

use \WriterAi\SDK\Utils\SpeakeasyMetadata;
class DetectContentRequest
{
	#[SpeakeasyMetadata('request:mediaType=application/json')]
    public \WriterAi\SDK\Models\Shared\ContentDetectorRequest $contentDetectorRequest;
    
	#[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=organizationId')]
    public ?int $organizationId = null;
    
	public function __construct()
	{
		$this->contentDetectorRequest = new \WriterAi\SDK\Models\Shared\ContentDetectorRequest();
		$this->organizationId = null;
	}
}
