<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace WriterAi\SDK\Models\Operations;


enum FindTermsPartOfSpeech: string
{
    case Noun = 'noun';
    case Verb = 'verb';
    case Adverb = 'adverb';
    case Adjective = 'adjective';
}
