<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace WriterAi\SDK\Models\Operations;


/**
 */
enum FindSnippetsSortFieldEnum: string
{
    case SHORTCUT = 'shortcut';
    case CREATION_TIME = 'creationTime';
    case MODIFICATION_TIME = 'modificationTime';
}
