<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace WriterAi\SDK\Models\Operations;


/**
 */
enum FindSnippetsSortOrder: string
{
    case ASC = 'asc';
    case DESC = 'desc';
}
