<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace WriterAi\SDK\Models\Operations;


enum FindSnippetsSortField: string
{
    case Shortcut = 'shortcut';
    case CreationTime = 'creationTime';
    case ModificationTime = 'modificationTime';
}
