<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace WriterAi\SDK\Models\Operations;

use \WriterAi\SDK\Utils\SpeakeasyMetadata;
class GetModelCustomizationRequest
{
	#[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=customizationId')]
    public string $customizationId;
    
	#[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=modelId')]
    public string $modelId;
    
	#[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=organizationId')]
    public ?int $organizationId = null;
    
	public function __construct()
	{
		$this->customizationId = "";
		$this->modelId = "";
		$this->organizationId = null;
	}
}
