<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace WriterAi\SDK\Models\Operations;

use \WriterAi\SDK\Utils\SpeakeasyMetadata;
class ListPagesRequest
{
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=limit')]
    public ?int $limit = null;
    
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=offset')]
    public ?int $offset = null;
    
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=status')]
    public ?ListPagesStatusEnum $status = null;
    
	public function __construct()
	{
		$this->limit = null;
		$this->offset = null;
		$this->status = null;
	}
}
