<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace WriterAi\SDK\Models\Operations;

use \WriterAi\SDK\Utils\SpeakeasyMetadata;
class ListUsersRequest
{
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=limit')]
    public ?int $limit = null;
    
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=offset')]
    public ?int $offset = null;
    
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=search')]
    public ?string $search = null;
    
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=sortField')]
    public ?ListUsersQueryParamSortField $sortField = null;
    
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=sortOrder')]
    public ?ListUsersQueryParamSortOrder $sortOrder = null;
    
	public function __construct()
	{
		$this->limit = null;
		$this->offset = null;
		$this->search = null;
		$this->sortField = null;
		$this->sortOrder = null;
	}
}
