<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace WriterAi\SDK\Models\Operations;

use \WriterAi\SDK\Utils\SpeakeasyMetadata;
class PageDetailsRequest
{
	#[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=pageId')]
    public int $pageId;
    
	public function __construct()
	{
		$this->pageId = 0;
	}
}
