<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace WriterAi\SDK\Models\Operations;


enum QueryParamSortField: string
{
    case Term = 'term';
    case CreationTime = 'creationTime';
    case ModificationTime = 'modificationTime';
    case Type = 'type';
}
