<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace WriterAi\SDK\Models\Operations;

use \WriterAi\SDK\Utils\SpeakeasyMetadata;
class UploadFileRequest
{
	#[SpeakeasyMetadata('request:mediaType=multipart/form-data')]
    public \WriterAi\SDK\Models\Shared\UploadModelFileRequest $uploadModelFileRequest;
    
	#[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=organizationId')]
    public ?int $organizationId = null;
    
	public function __construct()
	{
		$this->uploadModelFileRequest = new \WriterAi\SDK\Models\Shared\UploadModelFileRequest();
		$this->organizationId = null;
	}
}
