<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace WriterAi\SDK\Models\Shared;


enum Access: string
{
    case Private = 'private';
    case Public = 'public';
    case Shared = 'shared';
}
