<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace WriterAi\SDK\Models\Shared;


enum AccountStatus: string
{
    case Invited = 'invited';
    case SignedUp = 'signed_up';
}
