<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace WriterAi\SDK\Models\Shared;


class CompletionGenerationChoice
{
	#[\JMS\Serializer\Annotation\SerializedName('logprobs')]
    #[\JMS\Serializer\Annotation\Type('WriterAi\SDK\Models\Shared\CompletionGenerationChoiceLogprobs')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?CompletionGenerationChoiceLogprobs $logprobs = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('text')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $text;
    
	public function __construct()
	{
		$this->logprobs = null;
		$this->text = "";
	}
}
