<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace WriterAi\SDK\Models\Shared;


enum ContentIssueService: string
{
    case COMMON_MISTAKES = 'common-mistakes';
    case BANNED_WORDS = 'banned-words';
    case DICTIONARY = 'dictionary';
    case GEC = 'gec';
    case INFINITIVE = 'infinitive';
    case SPELLING = 'spelling';
    case WRITING_STYLE = 'writing-style';
    case CUSTOM_RULES = 'custom-rules';
    case SENTENCE_CASE = 'sentence-case';
    case ACRONYM = 'acronym';
    case OXFORD_COMMA = 'oxford-comma';
    case ML_PUNCTUATION = 'ml-punctuation';
    case EMOJIS = 'emojis';
    case GENDER_PRONOUNS = 'gender-pronouns';
    case SENSITIVITY = 'sensitivity';
    case PLAGIARISM = 'plagiarism';
    case READABILITY = 'readability';
    case SENTENCE_COMPLEXITY = 'sentence-complexity';
    case VOCABULARY = 'vocabulary';
    case PARAGRAPH_LENGTH = 'paragraph-length';
    case PLAIN_LANGUAGE = 'plain-language';
    case HEALTHY_COMMN = 'healthy-commn';
    case CONFIDENCE = 'confidence';
    case DATA_LOSS_PREVENTION = 'data-loss-prevention';
    case HATE_SPEECH = 'hate-speech';
    case CONTENT_SAFEGUARDS = 'content-safeguards';
    case FEEDBACK = 'feedback';
    case CLAIM = 'claim';
    case QUOTE = 'quote';
    case GENDER_NOUNS = 'gender-nouns';
    case GENDER_TONE = 'gender-tone';
    case GRAMMAR = 'grammar';
    case PUNCTUATION_DARK = 'punctuation-dark';
    case FORMATTING = 'formatting';
    case TWITTER = 'twitter';
    case GEC_DARK = 'gec-dark';
    case GEC_GPT3 = 'gec-gpt3';
}
