<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace WriterAi\SDK\Models\Shared;


class ContentIssue
{
	#[\JMS\Serializer\Annotation\SerializedName('description')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $description = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('from')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $from;
    
	#[\JMS\Serializer\Annotation\SerializedName('meta')]
    #[\JMS\Serializer\Annotation\Type('mixed')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public mixed $meta = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('service')]
    #[\JMS\Serializer\Annotation\Type('enum<WriterAi\SDK\Models\Shared\Service>')]
    public Service $service;
    
    /**
     * $suggestions
     * 
     * @var ?array<string> $suggestions
     */
	#[\JMS\Serializer\Annotation\SerializedName('suggestions')]
    #[\JMS\Serializer\Annotation\Type('array<string>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?array $suggestions = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('until')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $until;
    
	public function __construct()
	{
		$this->description = null;
		$this->from = 0;
		$this->meta = null;
		$this->service = \WriterAi\SDK\Models\Shared\Service::CommonMistakes;
		$this->suggestions = null;
		$this->until = 0;
	}
}
