<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace WriterAi\SDK\Models\Shared;


class ContentDetectorResponse
{
	#[\JMS\Serializer\Annotation\SerializedName('label')]
    #[\JMS\Serializer\Annotation\Type('enum<WriterAi\SDK\Models\Shared\ContentDetectorResponseLabel>')]
    public ContentDetectorResponseLabel $label;
    
	#[\JMS\Serializer\Annotation\SerializedName('score')]
    #[\JMS\Serializer\Annotation\Type('float')]
    public float $score;
    
	public function __construct()
	{
		$this->label = \WriterAi\SDK\Models\Shared\ContentDetectorResponseLabel::FAKE;
		$this->score = 0;
	}
}
