<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace WriterAi\SDK\Models\Shared;


class ContentSettings
{
	#[\JMS\Serializer\Annotation\SerializedName('ageAndFamilyStatus')]
    #[\JMS\Serializer\Annotation\Type('bool')]
    public bool $ageAndFamilyStatus;
    
	#[\JMS\Serializer\Annotation\SerializedName('confidence')]
    #[\JMS\Serializer\Annotation\Type('bool')]
    public bool $confidence;
    
	#[\JMS\Serializer\Annotation\SerializedName('contentSafeguards')]
    #[\JMS\Serializer\Annotation\Type('bool')]
    public bool $contentSafeguards;
    
	#[\JMS\Serializer\Annotation\SerializedName('disability')]
    #[\JMS\Serializer\Annotation\Type('bool')]
    public bool $disability;
    
	#[\JMS\Serializer\Annotation\SerializedName('genderIdentitySensitivity')]
    #[\JMS\Serializer\Annotation\Type('bool')]
    public bool $genderIdentitySensitivity;
    
	#[\JMS\Serializer\Annotation\SerializedName('genderInclusiveNouns')]
    #[\JMS\Serializer\Annotation\Type('bool')]
    public bool $genderInclusiveNouns;
    
	#[\JMS\Serializer\Annotation\SerializedName('genderInclusivePronouns')]
    #[\JMS\Serializer\Annotation\Type('bool')]
    public bool $genderInclusivePronouns;
    
	#[\JMS\Serializer\Annotation\SerializedName('grammar')]
    #[\JMS\Serializer\Annotation\Type('bool')]
    public bool $grammar;
    
	#[\JMS\Serializer\Annotation\SerializedName('healthyCommunication')]
    #[\JMS\Serializer\Annotation\Type('bool')]
    public bool $healthyCommunication;
    
	#[\JMS\Serializer\Annotation\SerializedName('passiveVoice')]
    #[\JMS\Serializer\Annotation\Type('bool')]
    public bool $passiveVoice;
    
	#[\JMS\Serializer\Annotation\SerializedName('raceEthnicityNationalitySensitivity')]
    #[\JMS\Serializer\Annotation\Type('bool')]
    public bool $raceEthnicityNationalitySensitivity;
    
	#[\JMS\Serializer\Annotation\SerializedName('sexualOrientationSensitivity')]
    #[\JMS\Serializer\Annotation\Type('bool')]
    public bool $sexualOrientationSensitivity;
    
	#[\JMS\Serializer\Annotation\SerializedName('spelling')]
    #[\JMS\Serializer\Annotation\Type('bool')]
    public bool $spelling;
    
	#[\JMS\Serializer\Annotation\SerializedName('substanceUseSensitivity')]
    #[\JMS\Serializer\Annotation\Type('bool')]
    public bool $substanceUseSensitivity;
    
	#[\JMS\Serializer\Annotation\SerializedName('unclearReference')]
    #[\JMS\Serializer\Annotation\Type('bool')]
    public bool $unclearReference;
    
	#[\JMS\Serializer\Annotation\SerializedName('wordiness')]
    #[\JMS\Serializer\Annotation\Type('bool')]
    public bool $wordiness;
    
	public function __construct()
	{
		$this->ageAndFamilyStatus = false;
		$this->confidence = false;
		$this->contentSafeguards = false;
		$this->disability = false;
		$this->genderIdentitySensitivity = false;
		$this->genderInclusiveNouns = false;
		$this->genderInclusivePronouns = false;
		$this->grammar = false;
		$this->healthyCommunication = false;
		$this->passiveVoice = false;
		$this->raceEthnicityNationalitySensitivity = false;
		$this->sexualOrientationSensitivity = false;
		$this->spelling = false;
		$this->substanceUseSensitivity = false;
		$this->unclearReference = false;
		$this->wordiness = false;
	}
}
