<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace WriterAi\SDK\Models\Shared;


enum ContentDetectorResponseLabel: string
{
    case FAKE = 'fake';
    case REAL = 'real';
}
