<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace WriterAi\SDK\Models\Shared;


class ContentRequest
{
	#[\JMS\Serializer\Annotation\SerializedName('content')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $content;
    
	#[\JMS\Serializer\Annotation\SerializedName('settings')]
    #[\JMS\Serializer\Annotation\Type('WriterAi\SDK\Models\Shared\ContentSettings')]
    public ContentSettings $settings;
    
	public function __construct()
	{
		$this->content = "";
		$this->settings = new \WriterAi\SDK\Models\Shared\ContentSettings();
	}
}
