<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace WriterAi\SDK\Models\Shared;


class CorrectionResponse
{
	#[\JMS\Serializer\Annotation\SerializedName('correct')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $correct;
    
	public function __construct()
	{
		$this->correct = "";
	}
}
