<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace WriterAi\SDK\Models\Shared;


class CreateTermsRequest
{
	#[\JMS\Serializer\Annotation\SerializedName('failHandling')]
    #[\JMS\Serializer\Annotation\Type('enum<WriterAi\SDK\Models\Shared\CreateTermsRequestFailHandlingEnum>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?CreateTermsRequestFailHandlingEnum $failHandling = null;
    
    /**
     * $models
     * 
     * @var ?array<\WriterAi\SDK\Models\Shared\TermCreate> $models
     */
	#[\JMS\Serializer\Annotation\SerializedName('models')]
    #[\JMS\Serializer\Annotation\Type('array<WriterAi\SDK\Models\Shared\TermCreate>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?array $models = null;
    
	public function __construct()
	{
		$this->failHandling = null;
		$this->models = null;
	}
}
