<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace WriterAi\SDK\Models\Shared;


enum CreateTermsRequestFailHandling: string
{
    case ACCUMULATE = 'accumulate';
    case VALIDATE = 'validate';
    case SKIP = 'skip';
    case VALIDATE_ONLY = 'validateOnly';
}
