<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace WriterAi\SDK\Models\Shared;


class CreateTermsResponse
{
    /**
     * $fails
     * 
     * @var ?array<\WriterAi\SDK\Models\Shared\FailMessage> $fails
     */
	#[\JMS\Serializer\Annotation\SerializedName('fails')]
    #[\JMS\Serializer\Annotation\Type('array<WriterAi\SDK\Models\Shared\FailMessage>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?array $fails = null;
    
    /**
     * $models
     * 
     * @var ?array<\WriterAi\SDK\Models\Shared\FullTermWithUser> $models
     */
	#[\JMS\Serializer\Annotation\SerializedName('models')]
    #[\JMS\Serializer\Annotation\Type('array<WriterAi\SDK\Models\Shared\FullTermWithUser>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?array $models = null;
    
	public function __construct()
	{
		$this->fails = null;
		$this->models = null;
	}
}
