<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace WriterAi\SDK\Models\Shared;


class CustomizationsResponse
{
    /**
     * $customizations
     * 
     * @var ?array<\WriterAi\SDK\Models\Shared\ModelCustomization> $customizations
     */
	#[\JMS\Serializer\Annotation\SerializedName('customizations')]
    #[\JMS\Serializer\Annotation\Type('array<WriterAi\SDK\Models\Shared\ModelCustomization>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?array $customizations = null;
    
	public function __construct()
	{
		$this->customizations = null;
	}
}
