<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace WriterAi\SDK\Models\Shared;


class Draft
{
	#[\JMS\Serializer\Annotation\SerializedName('body')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $body;
    
	#[\JMS\Serializer\Annotation\SerializedName('createdUserId')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $createdUserId;
    
	#[\JMS\Serializer\Annotation\SerializedName('creationTime')]
    #[\JMS\Serializer\Annotation\Type("DateTime<'Y-m-d\TH:i:s.up'>")]
    public \DateTime $creationTime;
    
	#[\JMS\Serializer\Annotation\SerializedName('deleted')]
    #[\JMS\Serializer\Annotation\Type('bool')]
    public bool $deleted;
    
	#[\JMS\Serializer\Annotation\SerializedName('documentId')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $documentId;
    
	#[\JMS\Serializer\Annotation\SerializedName('id')]
    #[\JMS\Serializer\Annotation\Type('int')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?int $id = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('inputs')]
    #[\JMS\Serializer\Annotation\Type('mixed')]
    public mixed $inputs;
    
	#[\JMS\Serializer\Annotation\SerializedName('organizationId')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $organizationId;
    
	#[\JMS\Serializer\Annotation\SerializedName('teamId')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $teamId;
    
	#[\JMS\Serializer\Annotation\SerializedName('templateId')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $templateId;
    
	#[\JMS\Serializer\Annotation\SerializedName('title')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $title = null;
    
	public function __construct()
	{
		$this->body = "";
		$this->createdUserId = 0;
		$this->creationTime = new \DateTime();
		$this->deleted = false;
		$this->documentId = "";
		$this->id = null;
		$this->inputs = null;
		$this->organizationId = 0;
		$this->teamId = 0;
		$this->templateId = "";
		$this->title = null;
	}
}
