<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace WriterAi\SDK\Models\Shared;


/**
 * FailResponse - Bad Request
 * 
 * @package WriterAi\SDK\Models\Shared
 * @access public
 */
class FailResponse
{
    /**
     * $errors
     * 
     * @var ?array<\WriterAi\SDK\Models\Shared\FailMessage> $errors
     */
	#[\JMS\Serializer\Annotation\SerializedName('errors')]
    #[\JMS\Serializer\Annotation\Type('array<WriterAi\SDK\Models\Shared\FailMessage>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?array $errors = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('extras')]
    #[\JMS\Serializer\Annotation\Type('mixed')]
    public mixed $extras;
    
	#[\JMS\Serializer\Annotation\SerializedName('tpe')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $tpe;
    
	public function __construct()
	{
		$this->errors = null;
		$this->extras = null;
		$this->tpe = "";
	}
}
