<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace WriterAi\SDK\Models\Shared;


class GenerationModelsResponse
{
    /**
     * $data
     * 
     * @var ?array<\WriterAi\SDK\Models\Shared\GenerationModelInfoResponse> $data
     */
	#[\JMS\Serializer\Annotation\SerializedName('data')]
    #[\JMS\Serializer\Annotation\Type('array<WriterAi\SDK\Models\Shared\GenerationModelInfoResponse>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?array $data = null;
    
	public function __construct()
	{
		$this->data = null;
	}
}
