<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace WriterAi\SDK\Models\Shared;


class GenerateTemplateRequest
{
    /**
     * $inputs
     * 
     * @var ?array<\WriterAi\SDK\Models\Shared\MagicRequestInput> $inputs
     */
	#[\JMS\Serializer\Annotation\SerializedName('inputs')]
    #[\JMS\Serializer\Annotation\Type('array<WriterAi\SDK\Models\Shared\MagicRequestInput>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?array $inputs = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('templateId')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $templateId;
    
	public function __construct()
	{
		$this->inputs = null;
		$this->templateId = "";
	}
}
