<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace WriterAi\SDK\Models\Shared;


class HyperParameters
{
	#[\JMS\Serializer\Annotation\SerializedName('numVirtualTokens')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $numVirtualTokens;
    
	public function __construct()
	{
		$this->numVirtualTokens = 0;
	}
}
