<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace WriterAi\SDK\Models\Shared;


enum InputType: string
{
    case TEXTBOX = 'textbox';
    case TEXTAREA = 'textarea';
    case DROPDOWN = 'dropdown';
}
