<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace WriterAi\SDK\Models\Shared;


class Input
{
	#[\JMS\Serializer\Annotation\SerializedName('dynamic')]
    #[\JMS\Serializer\Annotation\Type('bool')]
    public bool $dynamic;
    
	#[\JMS\Serializer\Annotation\SerializedName('help')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $help = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('maxFields')]
    #[\JMS\Serializer\Annotation\Type('int')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?int $maxFields = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('minFields')]
    #[\JMS\Serializer\Annotation\Type('int')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?int $minFields = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('name')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $name;
    
    /**
     * $options
     * 
     * @var ?array<string> $options
     */
	#[\JMS\Serializer\Annotation\SerializedName('options')]
    #[\JMS\Serializer\Annotation\Type('array<string>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?array $options = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('required')]
    #[\JMS\Serializer\Annotation\Type('bool')]
    public bool $required;
    
	#[\JMS\Serializer\Annotation\SerializedName('subtitle')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $subtitle = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('type')]
    #[\JMS\Serializer\Annotation\Type('enum<WriterAi\SDK\Models\Shared\InputType>')]
    public InputType $type;
    
	#[\JMS\Serializer\Annotation\SerializedName('unitCopy')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $unitCopy = null;
    
	public function __construct()
	{
		$this->dynamic = false;
		$this->help = null;
		$this->maxFields = null;
		$this->minFields = null;
		$this->name = "";
		$this->options = null;
		$this->required = false;
		$this->subtitle = null;
		$this->type = \WriterAi\SDK\Models\Shared\InputType::Textbox;
		$this->unitCopy = null;
	}
}
