<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace WriterAi\SDK\Models\Shared;


enum MetaDataTier: string
{
    case Enterprise1 = 'enterprise-1';
    case Enterprise2 = 'enterprise-2';
    case Enterprise3 = 'enterprise-3';
    case Enterprise4 = 'enterprise-4';
}
