<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace WriterAi\SDK\Models\Shared;


enum MetaDataTier: string
{
    case ENTERPRISE1 = 'enterprise-1';
    case ENTERPRISE2 = 'enterprise-2';
    case ENTERPRISE3 = 'enterprise-3';
    case ENTERPRISE4 = 'enterprise-4';
}
