<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace WriterAi\SDK\Models\Shared;


class ModelCustomization
{
	#[\JMS\Serializer\Annotation\SerializedName('additionalHyperParameters')]
    #[\JMS\Serializer\Annotation\Type('WriterAi\SDK\Models\Shared\HyperParameters')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?HyperParameters $additionalHyperParameters = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('baseModelId')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $baseModelId;
    
	#[\JMS\Serializer\Annotation\SerializedName('batchSize')]
    #[\JMS\Serializer\Annotation\Type('int')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?int $batchSize = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('createdAt')]
    #[\JMS\Serializer\Annotation\Type("DateTime<'Y-m-d\TH:i:s.up'>")]
    public \DateTime $createdAt;
    
	#[\JMS\Serializer\Annotation\SerializedName('description')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $description = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('epochs')]
    #[\JMS\Serializer\Annotation\Type('int')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?int $epochs = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('id')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $id;
    
	#[\JMS\Serializer\Annotation\SerializedName('learningRate')]
    #[\JMS\Serializer\Annotation\Type('float')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?float $learningRate = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('name')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $name;
    
	#[\JMS\Serializer\Annotation\SerializedName('promptTemplate')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $promptTemplate = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('status')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $status;
    
	#[\JMS\Serializer\Annotation\SerializedName('trainingDatasetFileId')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $trainingDatasetFileId;
    
	#[\JMS\Serializer\Annotation\SerializedName('updatedAt')]
    #[\JMS\Serializer\Annotation\Type("DateTime<'Y-m-d\TH:i:s.up'>")]
    public \DateTime $updatedAt;
    
	#[\JMS\Serializer\Annotation\SerializedName('validationDatasetFileId')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $validationDatasetFileId = null;
    
	public function __construct()
	{
		$this->additionalHyperParameters = null;
		$this->baseModelId = "";
		$this->batchSize = null;
		$this->createdAt = new \DateTime();
		$this->description = null;
		$this->epochs = null;
		$this->id = "";
		$this->learningRate = null;
		$this->name = "";
		$this->promptTemplate = null;
		$this->status = "";
		$this->trainingDatasetFileId = "";
		$this->updatedAt = new \DateTime();
		$this->validationDatasetFileId = null;
	}
}
