<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace WriterAi\SDK\Models\Shared;


class ModelFilesResponse
{
    /**
     * $files
     * 
     * @var ?array<\WriterAi\SDK\Models\Shared\ModelFile> $files
     */
	#[\JMS\Serializer\Annotation\SerializedName('files')]
    #[\JMS\Serializer\Annotation\Type('array<WriterAi\SDK\Models\Shared\ModelFile>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?array $files = null;
    
	public function __construct()
	{
		$this->files = null;
	}
}
