<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace WriterAi\SDK\Models\Shared;


class PaginatedResultUserPublicResponse
{
	#[\JMS\Serializer\Annotation\SerializedName('pagination')]
    #[\JMS\Serializer\Annotation\Type('WriterAi\SDK\Models\Shared\Pagination')]
    public Pagination $pagination;
    
    /**
     * $result
     * 
     * @var ?array<\WriterAi\SDK\Models\Shared\UserPublicResponse> $result
     */
	#[\JMS\Serializer\Annotation\SerializedName('result')]
    #[\JMS\Serializer\Annotation\Type('array<WriterAi\SDK\Models\Shared\UserPublicResponse>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?array $result = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('totalCount')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $totalCount;
    
	public function __construct()
	{
		$this->pagination = new \WriterAi\SDK\Models\Shared\Pagination();
		$this->result = null;
		$this->totalCount = 0;
	}
}
