<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace WriterAi\SDK\Models\Shared;


class ProcessedContent
{
    /**
     * $issues
     * 
     * @var ?array<\WriterAi\SDK\Models\Shared\ContentIssue> $issues
     */
	#[\JMS\Serializer\Annotation\SerializedName('issues')]
    #[\JMS\Serializer\Annotation\Type('array<WriterAi\SDK\Models\Shared\ContentIssue>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?array $issues = null;
    
	public function __construct()
	{
		$this->issues = null;
	}
}
