<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace WriterAi\SDK\Models\Shared;


class SnippetUpdate
{
	#[\JMS\Serializer\Annotation\SerializedName('description')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $description = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('id')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $id;
    
	#[\JMS\Serializer\Annotation\SerializedName('shortcut')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $shortcut = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('snippet')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $snippet;
    
    /**
     * $tags
     * 
     * @var ?array<\WriterAi\SDK\Models\Shared\SnippetTagV2> $tags
     */
	#[\JMS\Serializer\Annotation\SerializedName('tags')]
    #[\JMS\Serializer\Annotation\Type('array<WriterAi\SDK\Models\Shared\SnippetTagV2>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?array $tags = null;
    
	public function __construct()
	{
		$this->description = null;
		$this->id = "";
		$this->shortcut = null;
		$this->snippet = "";
		$this->tags = null;
	}
}
