<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace WriterAi\SDK\Models\Shared;


class SnippetWithUser
{
	#[\JMS\Serializer\Annotation\SerializedName('createdUser')]
    #[\JMS\Serializer\Annotation\Type('WriterAi\SDK\Models\Shared\TerminologyUser')]
    public TerminologyUser $createdUser;
    
	#[\JMS\Serializer\Annotation\SerializedName('creationTime')]
    #[\JMS\Serializer\Annotation\Type("DateTime<'Y-m-d\TH:i:s.up'>")]
    public \DateTime $creationTime;
    
	#[\JMS\Serializer\Annotation\SerializedName('description')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $description = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('id')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $id;
    
	#[\JMS\Serializer\Annotation\SerializedName('modificationTime')]
    #[\JMS\Serializer\Annotation\Type("DateTime<'Y-m-d\TH:i:s.up'>")]
    public \DateTime $modificationTime;
    
	#[\JMS\Serializer\Annotation\SerializedName('modifiedUser')]
    #[\JMS\Serializer\Annotation\Type('WriterAi\SDK\Models\Shared\TerminologyUser')]
    public TerminologyUser $modifiedUser;
    
	#[\JMS\Serializer\Annotation\SerializedName('shortcut')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $shortcut = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('snippet')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $snippet;
    
    /**
     * $tags
     * 
     * @var ?array<\WriterAi\SDK\Models\Shared\SnippetTagV2> $tags
     */
	#[\JMS\Serializer\Annotation\SerializedName('tags')]
    #[\JMS\Serializer\Annotation\Type('array<WriterAi\SDK\Models\Shared\SnippetTagV2>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?array $tags = null;
    
	public function __construct()
	{
		$this->createdUser = new \WriterAi\SDK\Models\Shared\TerminologyUser();
		$this->creationTime = new \DateTime();
		$this->description = null;
		$this->id = "";
		$this->modificationTime = new \DateTime();
		$this->modifiedUser = new \WriterAi\SDK\Models\Shared\TerminologyUser();
		$this->shortcut = null;
		$this->snippet = "";
		$this->tags = null;
	}
}
