<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace WriterAi\SDK\Models\Shared;


enum SubscriptionPublicResponseApiProductName: string
{
    case Free = 'free';
    case Pro = 'pro';
    case Team = 'team';
    case Enterprise = 'enterprise';
    case Legacy = 'legacy';
}
