<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace WriterAi\SDK\Models\Shared;


class SubscriptionPublicResponseApi
{
	#[\JMS\Serializer\Annotation\SerializedName('createdAt')]
    #[\JMS\Serializer\Annotation\Type("DateTime<'Y-m-d\TH:i:s.up'>")]
    public \DateTime $createdAt;
    
	#[\JMS\Serializer\Annotation\SerializedName('meta')]
    #[\JMS\Serializer\Annotation\Type('WriterAi\SDK\Models\Shared\MetaData')]
    public MetaData $meta;
    
	#[\JMS\Serializer\Annotation\SerializedName('productName')]
    #[\JMS\Serializer\Annotation\Type('enum<WriterAi\SDK\Models\Shared\ProductName>')]
    public ProductName $productName;
    
	#[\JMS\Serializer\Annotation\SerializedName('seats')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $seats;
    
	#[\JMS\Serializer\Annotation\SerializedName('status')]
    #[\JMS\Serializer\Annotation\Type('enum<WriterAi\SDK\Models\Shared\SubscriptionPublicResponseApiStatus>')]
    public SubscriptionPublicResponseApiStatus $status;
    
	#[\JMS\Serializer\Annotation\SerializedName('subscriptionId')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $subscriptionId;
    
	#[\JMS\Serializer\Annotation\SerializedName('usage')]
    #[\JMS\Serializer\Annotation\Type('WriterAi\SDK\Models\Shared\Usage')]
    public Usage $usage;
    
	public function __construct()
	{
		$this->createdAt = new \DateTime();
		$this->meta = new \WriterAi\SDK\Models\Shared\MetaData();
		$this->productName = \WriterAi\SDK\Models\Shared\ProductName::Free;
		$this->seats = 0;
		$this->status = \WriterAi\SDK\Models\Shared\SubscriptionPublicResponseApiStatus::Trialing;
		$this->subscriptionId = "";
		$this->usage = new \WriterAi\SDK\Models\Shared\Usage();
	}
}
