<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace WriterAi\SDK\Models\Shared;


enum SubscriptionPublicResponseApiProductName: string
{
    case FREE = 'free';
    case PRO = 'pro';
    case TEAM = 'team';
    case ENTERPRISE = 'enterprise';
    case LEGACY = 'legacy';
}
