<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace WriterAi\SDK\Models\Shared;


class TemplateDetailsResponse
{
	#[\JMS\Serializer\Annotation\SerializedName('categoryId')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $categoryId;
    
	#[\JMS\Serializer\Annotation\SerializedName('creationTime')]
    #[\JMS\Serializer\Annotation\Type("DateTime<'Y-m-d\TH:i:s.up'>")]
    public \DateTime $creationTime;
    
	#[\JMS\Serializer\Annotation\SerializedName('description')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $description = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('guideUrl')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $guideUrl = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('id')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $id;
    
    /**
     * $inputs
     * 
     * @var ?array<\WriterAi\SDK\Models\Shared\Input> $inputs
     */
	#[\JMS\Serializer\Annotation\SerializedName('inputs')]
    #[\JMS\Serializer\Annotation\Type('array<WriterAi\SDK\Models\Shared\Input>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?array $inputs = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('modificationTime')]
    #[\JMS\Serializer\Annotation\Type("DateTime<'Y-m-d\TH:i:s.up'>")]
    public \DateTime $modificationTime;
    
	#[\JMS\Serializer\Annotation\SerializedName('name')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $name;
    
	public function __construct()
	{
		$this->categoryId = 0;
		$this->creationTime = new \DateTime();
		$this->description = null;
		$this->guideUrl = null;
		$this->id = "";
		$this->inputs = null;
		$this->modificationTime = new \DateTime();
		$this->name = "";
	}
}
