<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace WriterAi\SDK\Models\Shared;


enum TermExampleCreateType: string
{
    case GOOD = 'good';
    case BAD = 'bad';
}
