<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace WriterAi\SDK\Models\Shared;


class TermUpdate
{
	#[\JMS\Serializer\Annotation\SerializedName('approvedTermExtension')]
    #[\JMS\Serializer\Annotation\Type('WriterAi\SDK\Models\Shared\ApprovedTermExtensionCreate')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?ApprovedTermExtensionCreate $approvedTermExtension = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('caseSensitive')]
    #[\JMS\Serializer\Annotation\Type('bool')]
    public bool $caseSensitive;
    
	#[\JMS\Serializer\Annotation\SerializedName('description')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $description = null;
    
    /**
     * $examples
     * 
     * @var ?array<\WriterAi\SDK\Models\Shared\TermExampleCreate> $examples
     */
	#[\JMS\Serializer\Annotation\SerializedName('examples')]
    #[\JMS\Serializer\Annotation\Type('array<WriterAi\SDK\Models\Shared\TermExampleCreate>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?array $examples = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('highlight')]
    #[\JMS\Serializer\Annotation\Type('bool')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?bool $highlight = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('id')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $id;
    
    /**
     * $linkedTerms
     * 
     * @var ?array<\WriterAi\SDK\Models\Shared\LinkedTermCreate> $linkedTerms
     */
	#[\JMS\Serializer\Annotation\SerializedName('linkedTerms')]
    #[\JMS\Serializer\Annotation\Type('array<WriterAi\SDK\Models\Shared\LinkedTermCreate>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?array $linkedTerms = null;
    
    /**
     * $mistakes
     * 
     * @var ?array<\WriterAi\SDK\Models\Shared\TermMistakeCreate> $mistakes
     */
	#[\JMS\Serializer\Annotation\SerializedName('mistakes')]
    #[\JMS\Serializer\Annotation\Type('array<WriterAi\SDK\Models\Shared\TermMistakeCreate>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?array $mistakes = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('pos')]
    #[\JMS\Serializer\Annotation\Type('enum<WriterAi\SDK\Models\Shared\TermUpdatePosEnum>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?TermUpdatePosEnum $pos = null;
    
    /**
     * $tags
     * 
     * @var ?array<\WriterAi\SDK\Models\Shared\TermTagCreate> $tags
     */
	#[\JMS\Serializer\Annotation\SerializedName('tags')]
    #[\JMS\Serializer\Annotation\Type('array<WriterAi\SDK\Models\Shared\TermTagCreate>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?array $tags = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('term')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $term;
    
	#[\JMS\Serializer\Annotation\SerializedName('type')]
    #[\JMS\Serializer\Annotation\Type('enum<WriterAi\SDK\Models\Shared\TermUpdateTypeEnum>')]
    public TermUpdateTypeEnum $type;
    
	public function __construct()
	{
		$this->approvedTermExtension = null;
		$this->caseSensitive = false;
		$this->description = null;
		$this->examples = null;
		$this->highlight = null;
		$this->id = 0;
		$this->linkedTerms = null;
		$this->mistakes = null;
		$this->pos = null;
		$this->tags = null;
		$this->term = "";
		$this->type = \WriterAi\SDK\Models\Shared\TermUpdateTypeEnum::APPROVED;
	}
}
