<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace WriterAi\SDK\Models\Shared;


enum TermMistakePos: string
{
    case NOUN = 'noun';
    case VERB = 'verb';
    case ADVERB = 'adverb';
    case ADJECTIVE = 'adjective';
}
