<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace WriterAi\SDK\Models\Shared;


enum TermCreateType: string
{
    case Approved = 'approved';
    case Banned = 'banned';
    case Pending = 'pending';
}
