<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace WriterAi\SDK\Models\Shared;


class TermMistakeCreate
{
	#[\JMS\Serializer\Annotation\SerializedName('caseSensitive')]
    #[\JMS\Serializer\Annotation\Type('bool')]
    public bool $caseSensitive;
    
	#[\JMS\Serializer\Annotation\SerializedName('mistake')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $mistake;
    
	#[\JMS\Serializer\Annotation\SerializedName('pos')]
    #[\JMS\Serializer\Annotation\Type('enum<WriterAi\SDK\Models\Shared\TermMistakeCreatePosEnum>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?TermMistakeCreatePosEnum $pos = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('reference')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $reference = null;
    
	public function __construct()
	{
		$this->caseSensitive = false;
		$this->mistake = "";
		$this->pos = null;
		$this->reference = null;
	}
}
