<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace WriterAi\SDK\Models\Shared;


class TermExample
{
	#[\JMS\Serializer\Annotation\SerializedName('example')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $example;
    
	#[\JMS\Serializer\Annotation\SerializedName('id')]
    #[\JMS\Serializer\Annotation\Type('int')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?int $id = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('termBankId')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $termBankId;
    
	#[\JMS\Serializer\Annotation\SerializedName('termId')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $termId;
    
	#[\JMS\Serializer\Annotation\SerializedName('type')]
    #[\JMS\Serializer\Annotation\Type('enum<WriterAi\SDK\Models\Shared\TermExampleTypeEnum>')]
    public TermExampleTypeEnum $type;
    
	public function __construct()
	{
		$this->example = "";
		$this->id = null;
		$this->termBankId = 0;
		$this->termId = 0;
		$this->type = \WriterAi\SDK\Models\Shared\TermExampleTypeEnum::GOOD;
	}
}
