<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace WriterAi\SDK\Models\Shared;


class TermExampleCreate
{
	#[\JMS\Serializer\Annotation\SerializedName('example')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $example;
    
	#[\JMS\Serializer\Annotation\SerializedName('type')]
    #[\JMS\Serializer\Annotation\Type('enum<WriterAi\SDK\Models\Shared\TermExampleCreateTypeEnum>')]
    public TermExampleCreateTypeEnum $type;
    
	public function __construct()
	{
		$this->example = "";
		$this->type = \WriterAi\SDK\Models\Shared\TermExampleCreateTypeEnum::GOOD;
	}
}
