<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace WriterAi\SDK\Models\Shared;


enum UpdateTermsRequestFailHandling: string
{
    case Accumulate = 'accumulate';
    case Validate = 'validate';
    case Skip = 'skip';
    case ValidateOnly = 'validateOnly';
}
