<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace WriterAi\SDK\Models\Shared;

use \WriterAi\SDK\Utils\SpeakeasyMetadata;
class UploadModelFileRequest
{
	#[SpeakeasyMetadata('multipartForm:file=true')]
    public UploadModelFileRequestFile $file;
    
	public function __construct()
	{
		$this->file = new \WriterAi\SDK\Models\Shared\UploadModelFileRequestFile();
	}
}
