<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace WriterAi\SDK\Models\Shared;


class Usage
{
	#[\JMS\Serializer\Annotation\SerializedName('coWriteWords')]
    #[\JMS\Serializer\Annotation\Type('WriterAi\SDK\Models\Shared\UsageItem')]
    public UsageItem $coWriteWords;
    
	#[\JMS\Serializer\Annotation\SerializedName('team')]
    #[\JMS\Serializer\Annotation\Type('WriterAi\SDK\Models\Shared\UsageItem')]
    public UsageItem $team;
    
	#[\JMS\Serializer\Annotation\SerializedName('user')]
    #[\JMS\Serializer\Annotation\Type('WriterAi\SDK\Models\Shared\UsageItem')]
    public UsageItem $user;
    
	#[\JMS\Serializer\Annotation\SerializedName('words')]
    #[\JMS\Serializer\Annotation\Type('WriterAi\SDK\Models\Shared\UsageItem')]
    public UsageItem $words;
    
	public function __construct()
	{
		$this->coWriteWords = new \WriterAi\SDK\Models\Shared\UsageItem();
		$this->team = new \WriterAi\SDK\Models\Shared\UsageItem();
		$this->user = new \WriterAi\SDK\Models\Shared\UsageItem();
		$this->words = new \WriterAi\SDK\Models\Shared\UsageItem();
	}
}
