<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace WriterAi\SDK\Models\Shared;


enum UserPublicResponseAccountStatus: string
{
    case INVITED = 'invited';
    case SIGNED_UP = 'signed_up';
}
