<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace WriterAi\SDK;

/**
 * WriterBuilder is used to configure and build an instance of the SDK.
 * 
 * @package WriterAi\SDK
 */
class WriterBuilder
{
    private ?\GuzzleHttp\ClientInterface $client;
    private ?Models\Shared\Security $security;
    private string $serverUrl;
    /** @var array<string, string> */
    private ?array $params;
    /** @var array<string, array<string, array<string, mixed>>> */
    private ?array $globals;

    public function __construct() {
        $this->client = null;
        $this->security = null;
        $this->serverUrl = '';
        $this->params = null;
        $this->globals = [
            'parameters' => []
        ];
    }

    /**
     * setClient allows setting a custom Guzzle client for the SDK to make requests with.
     *
     * @param \GuzzleHttp\ClientInterface $client
     * @return WriterBuilder
     */
    public function setClient(\GuzzleHttp\ClientInterface $client): WriterBuilder
    {
        $this->client = $client;
        return $this;
    }
    
    /**
     * setSecurity is used to configure the security required for the SDK.
     *
     * @param Models\Shared\Security $security
     * @return WriterBuilder
     */
    public function setSecurity(Models\Shared\Security $security): WriterBuilder
    {
        $this->security = $security;
        return $this;
    }
    
    /**
     * setServerUrl is used to configure the server URL for the SDK, and optionally template any parameters in the URL.
     *
     * @param string $serverUrl
     * @param array<string, string> $params
     * @return WriterBuilder
     */
    public function setServerUrl(string $serverUrl, ?array $params = null): WriterBuilder
    {
        $this->serverUrl = $serverUrl;
        if ($params !== null) {
            $this->params = $params;
        }
        return $this;
    }
    
    /**
     * setOrganizationId is used to configure the organizationId parameter for the SDK.
     *
     * @param int $organizationId
     * @return WriterBuilder
     */
    public function setOrganizationId(int $organizationId): WriterBuilder
    {
        if (!array_key_exists('pathParam', $this->globals['parameters']))
        {
            $this->globals['parameters']['pathParam'] = [];
        }

        $this->globals['parameters']['pathParam']['organizationId'] = $organizationId;

        return $this;
    }
    
    /**
     * build is used to build the SDK with any of the configured options.
     *
     * @return Writer
     */
    public function build(): Writer
    {
        return new Writer($this->client, $this->security, $this->serverUrl, $this->params, $this->globals);
    }
}